### ISSUE TITLE
[TODO] Alpha Version Work

### ISSUE THREAD

**Issue by Indexyz** [InfinityStudio/ILauncher#3]
## backend
- [ ] MultiMc Export Package support
- [x] Auto install jre (openjre)
- [ ] CurseForge ModPack support
- [x] Support Fetch Mod in Server QuiCk Link
## view
- Metarial UI
  - [x] Create Server Quick Join
  - [ ] Package Card View in Main 
  - [ ] Add custom resources pack/mod
  - [ ] Edit Package
  - [ ] User skin preview
